#!/usr/bin/env bash
set -e

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sudo pacman -S ripgrep fzf ctags
ln -f -s $(pwd)/vim/.vimrc ~/.vimrc
